# 1. Creating Tensors

In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)


1.12.0


In [ ]:
# Uncomment the line below if you are not using tensorflow 2.0
#tf.enable_eager_execution() 

### constant

Creates constant Tensors of specified type. 

In [10]:
tensor1 = tf.constant([1, 2, 3, 4, 5, 6], dtype=tf.float32)
tensor2 = tf.constant([1, 2, 3, 4, 5, 6], shape=(2,3))

In [11]:
print(tensor1)
print(tensor2)

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


### convert_to_tensor

Converts a list or numpy array to a tensorflow tensor. The type is converted to specified type. If nothing is specified, it retains the original type

In [18]:
a = np.int64(np.array([[1,2,3]]))
a_tf = tf.convert_to_tensor(a)
print(a_tf)

b = np.int32(np.array([[1,2,3]]))
b_tf = tf.convert_to_tensor(b, dtype=tf.float32)
print(b_tf)

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int64)
tf.Tensor([[1. 2. 3.]], shape=(1, 3), dtype=float32)


### eye

Creates a diagonal matrix

In [5]:
print(tf.eye(2))

tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)


In [20]:
print(tf.eye(2, num_columns=4, dtype=tf.int32)) #Truncates or expands to the number of columns as specified

tf.Tensor(
[[1 0 0 0]
 [0 1 0 0]], shape=(2, 4), dtype=int32)


In [22]:
print(tf.eye(2, batch_shape=[3, 1])) # Repeats the diagonal matrix as specified (and creates extra dimensions)

tf.Tensor(
[[[[1. 0.]
   [0. 1.]]]


 [[[1. 0.]
   [0. 1.]]]


 [[[1. 0.]
   [0. 1.]]]], shape=(3, 1, 2, 2), dtype=float32)


### fill

Creates an empty Tensor and fills it with the specified value

In [8]:
print(tf.fill((3,3), 9)) 

tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)


### linspace

Similar to numpy linspace. Creates 1D tensor with n elements (where n==num), whose values are equally spaced between and including [start, stop]

In [9]:
print(tf.linspace(start=10.0, stop=12.0, num=5))

tf.Tensor([10.  10.5 11.  11.5 12. ], shape=(5,), dtype=float32)


### meshgrid

similar to numpy meshgrid. creates a mesh grid containing indices in either ij (regular indexing) format or xy (inverse indexing) format

In [26]:
a = tf.constant([[0,1, 2],[3, 4, 5]])
shape = tf.shape(a)
print(a)


tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [27]:
out = tf.meshgrid(tf.range(shape[0]), tf.range(shape[1]), indexing='ij')
print(out)

out = tf.meshgrid(tf.range(shape[0]), tf.range(shape[1]), indexing='xy')
print(out)

[<tf.Tensor: id=323, shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [1, 1, 1]], dtype=int32)>, <tf.Tensor: id=324, shape=(2, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [0, 1, 2]], dtype=int32)>]
[<tf.Tensor: id=361, shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [0, 1],
       [0, 1]], dtype=int32)>, <tf.Tensor: id=362, shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [1, 1],
       [2, 2]], dtype=int32)>]


### ones

Creates a tensor of specified size and type and fills it with 1s.

In [11]:
print(tf.ones(3, dtype=tf.int32))

tf.Tensor([1 1 1], shape=(3,), dtype=int32)


In [12]:
print(tf.ones((3,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


### ones_like

Creates a tensor of shape similar to passed array and fills it with ones. The type is also retained.

In [13]:
a = tf.constant([[0,1],[2,3]], dtype=tf.float32)
print(tf.ones_like(a))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


### one_hot

creates one hot vectors of specified depth. Indices specified are set to 1 in corresponding vectors and other elements are set to zero

In [14]:
indices = [0, 1, 1]
depth = 5
print(tf.one_hot(indices, depth, axis=-1)) #rows of one hot vectors (default=-1)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]], shape=(3, 5), dtype=float32)


If axis is specified, then the output will have the specified dept along the specified axis.

In [32]:
indices = [3, 1, 2]
depth = 5
print(tf.one_hot(indices, depth, axis=0))  #columns of one hot vectors

tf.Tensor(
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [16]:
indices = [0, 1, 1]
depth = 5
print(tf.one_hot(indices, depth, on_value=1, off_value=-1) ) #Fills with specifed on/off values

tf.Tensor(
[[ 1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1]
 [-1  1 -1 -1 -1]], shape=(3, 5), dtype=int32)


### TensorArray

Creates an array of specified size(n) and type. It can hold n tensors of fixed size.

In [45]:
tf_arr = tf.TensorArray(tf.float32, 7)
for i in range(2,5):
    a = tf.eye(2) * i
    tf_arr = tf_arr.write(i, a )
print(tf_arr.stack())

tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[2. 0.]
  [0. 2.]]

 [[3. 0.]
  [0. 3.]]

 [[4. 0.]
  [0. 4.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]], shape=(7, 2, 2), dtype=float32)


### Variable

Creates a tensorflow variable. It maintains its state in the graph. Gradients are computed depending on whether the trainable flag is set to true or false

In [18]:
var1 = tf.Variable([[1,2],[3,4]], trainable=True, dtype=tf.int32)
print(var1)



<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


### zeros

Creates a tensor of specified size and type and fills it with zeros.

In [19]:
print(tf.zeros(3, dtype=tf.int32))

tf.Tensor([0 0 0], shape=(3,), dtype=int32)


In [20]:
print(tf.zeros((3,3)))

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


### zeros_like

Creates a tensor of shape similar to passed array and fills it with zeros. The type is also retained

In [21]:
a = tf.constant([[0,1],[2,3]], dtype=tf.float32)
print(tf.zeros_like(a))

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
