# 2. Tensor Manipulation

In [7]:
import tensorflow as tf
import numpy as np
tf.enable_eager_execution()

### Tensor Fancy Indexing

Tensorflow Fancy Indexing works just like numpy indexing

In [8]:
a = tf.constant([[0,1,2,-1],[3,4,5,-2],[6,7,8,-3]], dtype=tf.float32)
print(a)

tf.Tensor(
[[ 0.  1.  2. -1.]
 [ 3.  4.  5. -2.]
 [ 6.  7.  8. -3.]], shape=(3, 4), dtype=float32)


In [9]:
b = a[1:2, :]
print(b) #2D output
print(tf.shape(b))

tf.Tensor([[ 3.  4.  5. -2.]], shape=(1, 4), dtype=float32)
tf.Tensor([1 4], shape=(2,), dtype=int32)


In [10]:
c = a[1, :]
print(c) #same as above but 1D output
print(tf.shape(c))

tf.Tensor([ 3.  4.  5. -2.], shape=(4,), dtype=float32)
tf.Tensor([4], shape=(1,), dtype=int32)


In [11]:
d = a[-1, 2]
print(d)

tf.Tensor(8.0, shape=(), dtype=float32)


In [12]:
e = a[0:2, 1:tf.shape(a)[1]]
print(e)

tf.Tensor(
[[ 1.  2. -1.]
 [ 4.  5. -2.]], shape=(2, 3), dtype=float32)


### concat

In [13]:
a = tf.constant([[[1],[2],[3]],[[4],[5],[6]]])
print(a)
print(tf.shape(a))

tf.Tensor(
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]], shape=(2, 3, 1), dtype=int32)
tf.Tensor([2 3 1], shape=(3,), dtype=int32)


In [14]:
c = tf.constant([[[11, 21, 101],[12, 22, 102],[13, 33, 103]],[[14, 44, 104],[15, 55, 105],[16, 66, 106]]])
print(c)
print(tf.shape(c))

tf.Tensor(
[[[ 11  21 101]
  [ 12  22 102]
  [ 13  33 103]]

 [[ 14  44 104]
  [ 15  55 105]
  [ 16  66 106]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([2 3 3], shape=(3,), dtype=int32)


In [15]:
concat_ac = tf.concat((a,c), axis=2) 

For concat, all dimensions of the concat variables, EXCEPT the axis along which it is being concatenated, must be equal. The resulting output will have same shape for all other dimensions. For the concat axis, the shape will be sum of the shapes of the concat axis


In [16]:
print('Shape of a:', a.shape)
print('Shape of c:', c.shape)
print('Shape of a:', concat_ac.shape)

Shape of a: (2, 3, 1)
Shape of c: (2, 3, 3)
Shape of a: (2, 3, 4)


In [17]:
b = tf.constant([[[11],[12],[13]],[[14],[15],[16]]])
print(b)
print(tf.shape(b))

tf.Tensor(
[[[11]
  [12]
  [13]]

 [[14]
  [15]
  [16]]], shape=(2, 3, 1), dtype=int32)
tf.Tensor([2 3 1], shape=(3,), dtype=int32)


In [18]:
#Concat along axis 0
concat_ab0 = tf.concat((a,b), axis=0)
print(concat_ab0)

tf.Tensor(
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[11]
  [12]
  [13]]

 [[14]
  [15]
  [16]]], shape=(4, 3, 1), dtype=int32)


In [19]:
# Concat along axis 2
concat_ab2 = tf.concat((a,b), axis=2)
print(concat_ab2)

tf.Tensor(
[[[ 1 11]
  [ 2 12]
  [ 3 13]]

 [[ 4 14]
  [ 5 15]
  [ 6 16]]], shape=(2, 3, 2), dtype=int32)


In [20]:
print('Shape of a:', a.shape)
print('Shape of b:', b.shape)
print('Shape of tf.concat(a,b,axis=0):', concat_ab0.shape)
print('Shape of tf.concat(a,b,axis=2):', concat_ab2.shape)

Shape of a: (2, 3, 1)
Shape of b: (2, 3, 1)
Shape of tf.concat(a,b,axis=0): (4, 3, 1)
Shape of tf.concat(a,b,axis=2): (2, 3, 2)


### expand_dims

expands the specified dimension

In [21]:
a = tf.constant([[1,2],[3,4]])
expand_0 = tf.expand_dims(a,0)
expand_1 = tf.expand_dims(a,1)
expand_2 = tf.expand_dims(a,2)

In [22]:
print(expand_0)

tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)


In [23]:
print(expand_1)

tf.Tensor(
[[[1 2]]

 [[3 4]]], shape=(2, 1, 2), dtype=int32)


In [24]:
print(expand_2)

tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


### gather

In [25]:
a = tf.constant([[[10, 11],[12, 22],[13, 33]],
                 [[14, 44],[15, 55],[16, 66]],
                 [[17, 77],[18, 88],[19, 99]],
                 [[1, 2],[4, 5],[7, 8]]])
print(a) # Here we are creating 4 - 3*2 matrices(inner)

tf.Tensor(
[[[10 11]
  [12 22]
  [13 33]]

 [[14 44]
  [15 55]
  [16 66]]

 [[17 77]
  [18 88]
  [19 99]]

 [[ 1  2]
  [ 4  5]
  [ 7  8]]], shape=(4, 3, 2), dtype=int32)


In [26]:
print('Shape of a:', a.shape)

Shape of a: (4, 3, 2)


In [27]:
#Gets the 1st and the 3rd inner 3*2 matrices
tf.gather(a, indices=[1, 3], axis=0) 

<tf.Tensor: id=99, shape=(2, 3, 2), dtype=int32, numpy=
array([[[14, 44],
        [15, 55],
        [16, 66]],

       [[ 1,  2],
        [ 4,  5],
        [ 7,  8]]], dtype=int32)>

In [28]:
#gets only the rows(since axis=1) 0,2 of the 3*2 inner matrix for all the 4 matrices
tf.gather(a, indices=[0,2], axis=1)

<tf.Tensor: id=103, shape=(4, 2, 2), dtype=int32, numpy=
array([[[10, 11],
        [13, 33]],

       [[14, 44],
        [16, 66]],

       [[17, 77],
        [19, 99]],

       [[ 1,  2],
        [ 7,  8]]], dtype=int32)>

In [29]:
#gets only the col(since axis=2) number 1 of the 3*2 inner matrix for all the 4 matrices
tf.gather(a, indices=[1], axis=2) 

<tf.Tensor: id=107, shape=(4, 3, 1), dtype=int32, numpy=
array([[[11],
        [22],
        [33]],

       [[44],
        [55],
        [66]],

       [[77],
        [88],
        [99]],

       [[ 2],
        [ 5],
        [ 8]]], dtype=int32)>

We need to make sure that the indices are within the ranges of the axis being indexed.

Depending on the indices passed, the corresponding items are selected from the specified axis.

If shape of indices is nd, then the output of gather will have shape that is expanded along the specified axis by nd

In [30]:
#gets rows (0,1,1), (0,2,1), (1,0,2), (0,0,0), (1,1,1) and all columns of inner matrix 
# and creates 4(outer)*5*3(indexed)*2(inner cols)
indices = np.array([[0,1,1],[0,2,1], [1,0,2], [0,0,0],[1,1,1]])
axis=1
out = tf.gather(a, indices=indices, axis=axis) 
print('shape of a:', a.shape)
print('shape of indices:', indices.shape)
print('specified axis:', axis)
print('shape of output:', out.shape)
print(out)

shape of a: (4, 3, 2)
shape of indices: (5, 3)
specified axis: 1
shape of output: (4, 5, 3, 2)
tf.Tensor(
[[[[10 11]
   [12 22]
   [12 22]]

  [[10 11]
   [13 33]
   [12 22]]

  [[12 22]
   [10 11]
   [13 33]]

  [[10 11]
   [10 11]
   [10 11]]

  [[12 22]
   [12 22]
   [12 22]]]


 [[[14 44]
   [15 55]
   [15 55]]

  [[14 44]
   [16 66]
   [15 55]]

  [[15 55]
   [14 44]
   [16 66]]

  [[14 44]
   [14 44]
   [14 44]]

  [[15 55]
   [15 55]
   [15 55]]]


 [[[17 77]
   [18 88]
   [18 88]]

  [[17 77]
   [19 99]
   [18 88]]

  [[18 88]
   [17 77]
   [19 99]]

  [[17 77]
   [17 77]
   [17 77]]

  [[18 88]
   [18 88]
   [18 88]]]


 [[[ 1  2]
   [ 4  5]
   [ 4  5]]

  [[ 1  2]
   [ 7  8]
   [ 4  5]]

  [[ 4  5]
   [ 1  2]
   [ 7  8]]

  [[ 1  2]
   [ 1  2]
   [ 1  2]]

  [[ 4  5]
   [ 4  5]
   [ 4  5]]]], shape=(4, 5, 3, 2), dtype=int32)


In [31]:
#selects column elements (0,1,1), (0,0,1), (1,0,1), (0,0,0), (1,1,1) for each rows of inner matrix 
# and creates 4(outer)*3(rows)*5*3(indexed)
indices = np.array([[0,1,1],[0,0,1], [1,0,1], [0,0,0],[1,1,1]])
axis=2
out = tf.gather(a, indices=indices, axis=axis) 
print('shape of a:', a.shape)
print('shape of indices:', indices.shape)
print('specified axis:', axis)
print('shape of output:', out.shape)
print(out)

shape of a: (4, 3, 2)
shape of indices: (5, 3)
specified axis: 2
shape of output: (4, 3, 5, 3)
tf.Tensor(
[[[[10 11 11]
   [10 10 11]
   [11 10 11]
   [10 10 10]
   [11 11 11]]

  [[12 22 22]
   [12 12 22]
   [22 12 22]
   [12 12 12]
   [22 22 22]]

  [[13 33 33]
   [13 13 33]
   [33 13 33]
   [13 13 13]
   [33 33 33]]]


 [[[14 44 44]
   [14 14 44]
   [44 14 44]
   [14 14 14]
   [44 44 44]]

  [[15 55 55]
   [15 15 55]
   [55 15 55]
   [15 15 15]
   [55 55 55]]

  [[16 66 66]
   [16 16 66]
   [66 16 66]
   [16 16 16]
   [66 66 66]]]


 [[[17 77 77]
   [17 17 77]
   [77 17 77]
   [17 17 17]
   [77 77 77]]

  [[18 88 88]
   [18 18 88]
   [88 18 88]
   [18 18 18]
   [88 88 88]]

  [[19 99 99]
   [19 19 99]
   [99 19 99]
   [19 19 19]
   [99 99 99]]]


 [[[ 1  2  2]
   [ 1  1  2]
   [ 2  1  2]
   [ 1  1  1]
   [ 2  2  2]]

  [[ 4  5  5]
   [ 4  4  5]
   [ 5  4  5]
   [ 4  4  4]
   [ 5  5  5]]

  [[ 7  8  8]
   [ 7  7  8]
   [ 8  7  8]
   [ 7  7  7]
   [ 8  8  8]]]], shape=(4, 3, 5, 3), dt

### gather_nd

In [32]:
a = tf.constant([[[10, 11],[12, 22],[13, 33]],
                 [[14, 44],[15, 55],[16, 66]],
                 [[17, 77],[18, 88],[19, 99]],
                 [[1, 2],[4, 5],[7, 8]]])
print(a) # Here we are creating 4 - 3*2 matrices(inner)

tf.Tensor(
[[[10 11]
  [12 22]
  [13 33]]

 [[14 44]
  [15 55]
  [16 66]]

 [[17 77]
  [18 88]
  [19 99]]

 [[ 1  2]
  [ 4  5]
  [ 7  8]]], shape=(4, 3, 2), dtype=int32)


In [33]:
indices = np.array([[0,1,1],[3,1,0]])
print('shape of a:', a.shape)
print('shape of indices:', indices.shape)
out = tf.gather_nd(a, indices=indices)
print('shape of out:', out.shape)
print(out)

shape of a: (4, 3, 2)
shape of indices: (2, 3)
shape of out: (2,)
tf.Tensor([22  4], shape=(2,), dtype=int32)


In [34]:
indices = np.array([[0],[1]])
print('shape of a:', a.shape)
print('shape of indices:', indices.shape)
out = tf.gather_nd(a, indices=indices)
print('shape of out:', out.shape)
print(out)

shape of a: (4, 3, 2)
shape of indices: (2, 1)
shape of out: (2, 3, 2)
tf.Tensor(
[[[10 11]
  [12 22]
  [13 33]]

 [[14 44]
  [15 55]
  [16 66]]], shape=(2, 3, 2), dtype=int32)


In [35]:
indices = np.array([3,0])
print('shape of a:', a.shape)
print('shape of indices:', indices.shape)
out = tf.gather_nd(a, indices=indices)
print('shape of out:', out.shape)
print(out)

shape of a: (4, 3, 2)
shape of indices: (2,)
shape of out: (2,)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [36]:
indices = np.array([[[3],[1]],[[1],[0]]])
print('shape of a:', a.shape)
print('shape of indices:', indices.shape)
out = tf.gather_nd(a, indices=indices)
print('shape of out:', out.shape)
print(out)

shape of a: (4, 3, 2)
shape of indices: (2, 2, 1)
shape of out: (2, 2, 3, 2)
tf.Tensor(
[[[[ 1  2]
   [ 4  5]
   [ 7  8]]

  [[14 44]
   [15 55]
   [16 66]]]


 [[[14 44]
   [15 55]
   [16 66]]

  [[10 11]
   [12 22]
   [13 33]]]], shape=(2, 2, 3, 2), dtype=int32)


In [37]:
indices = np.array([[[3,0],[1,0]],[[1,0],[0,0]]])
print('shape of a:', a.shape)
print('shape of indices:', indices.shape)
out = tf.gather_nd(a, indices=indices)
print('shape of out:', out.shape)
print(out)

shape of a: (4, 3, 2)
shape of indices: (2, 2, 2)
shape of out: (2, 2, 2)
tf.Tensor(
[[[ 1  2]
  [14 44]]

 [[14 44]
  [10 11]]], shape=(2, 2, 2), dtype=int32)


### reshape

In [39]:
a = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [47]:
a_reshaped = tf.reshape(a,[-1, 3])
print(a_reshaped)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [52]:
a_reshaped_back = tf.reshape(a_reshaped,[-1])
print(a_reshaped_back)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


### shape

Returns the shape of the tensor along all the dimensions

In [58]:
a = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tf.shape(a))
print(a.shape)

tf.Tensor([3 3], shape=(2,), dtype=int32)
(3, 3)


### size

Returns the total number of elements in the tensor

In [59]:
a = tf.constant([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(tf.size(a))

tf.Tensor(9, shape=(), dtype=int32)


### slice

In [76]:
a = tf.constant([[[1, 1111, 5551], [2, 1112, 5552], [3, 1113, 5553]],
                 [[4, 1114, 5554], [5, 1115, 5555], [6, 1116, 5556]],
                 [[7, 1117, 5557], [8, 1118, 5558], [9, 1119, 5559]],
                 [[10,1110,5510], [11,1111,5511], [12,1112,5512]],
                 [[13,1113,5513], [14,1114,5514], [15,1115,5515]]])

print(a)
print('Shape of a:', a.shape)

tf.Tensor(
[[[   1 1111 5551]
  [   2 1112 5552]
  [   3 1113 5553]]

 [[   4 1114 5554]
  [   5 1115 5555]
  [   6 1116 5556]]

 [[   7 1117 5557]
  [   8 1118 5558]
  [   9 1119 5559]]

 [[  10 1110 5510]
  [  11 1111 5511]
  [  12 1112 5512]]

 [[  13 1113 5513]
  [  14 1114 5514]
  [  15 1115 5515]]], shape=(5, 3, 3), dtype=int32)
Shape of a: (5, 3, 3)


Since a is a 3 dimensional tensor, the *begin* and *size* arguments of slice must be of size 3.

Begin indicates the index to start slicing from, and size tells how many elements to slice. 

In the example below we start at index (1,1,0) and slice 3 - 2 * 2 matrices starting at that index

In [79]:
print(tf.slice(a, begin=[1,1,0], size=[3,2,2]))

tf.Tensor(
[[[   5 1115]
  [   6 1116]]

 [[   8 1118]
  [   9 1119]]

 [[  11 1111]
  [  12 1112]]], shape=(3, 2, 2), dtype=int32)


### split

In [82]:
a = tf.constant([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)


In [84]:
#split along 0th axis
print(tf.split(a,2, axis=0)) #default axis is 0

[<tf.Tensor: id=271, shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>, <tf.Tensor: id=272, shape=(1, 6), dtype=int32, numpy=array([[ 7,  8,  9, 10, 11, 12]], dtype=int32)>]


In [89]:
#split along 1st axis
print(tf.split(a, num_or_size_splits=3, axis=1))

[<tf.Tensor: id=291, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [7, 8]], dtype=int32)>, <tf.Tensor: id=292, shape=(2, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 9, 10]], dtype=int32)>, <tf.Tensor: id=293, shape=(2, 2), dtype=int32, numpy=
array([[ 5,  6],
       [11, 12]], dtype=int32)>]


If you want to specify the size of split, then the sum of the elements in the list must be equal to the number of elements in the split axis

In [97]:
print(a.shape)
split_axis = 1
split_sizes = [1,3,2]
print(tf.split(a, num_or_size_splits=split_sizes, axis=split_axis))

(2, 6)
[<tf.Tensor: id=325, shape=(2, 1), dtype=int32, numpy=
array([[1],
       [7]], dtype=int32)>, <tf.Tensor: id=326, shape=(2, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 8,  9, 10]], dtype=int32)>, <tf.Tensor: id=327, shape=(2, 2), dtype=int32, numpy=
array([[ 5,  6],
       [11, 12]], dtype=int32)>]


### squeeze

In [108]:
a = tf.constant([[[[1,2,3]],[[4,5,6]]]])
print('Shape of a:',a.shape)

(1, 2, 1, 3)


In [117]:
squeezed_a_all = tf.squeeze(a) #Squeezes all axes whose size is 1
squeezed_a_0 = tf.squeeze(a,[2]) # Squeezes 2nd axis
print('Shape of tf.squeeze(a)     :',squeezed_a_all.shape)
print('Shape of tf.squeeze(a,[2]) :',squeezed_a_0.shape)

Shape of tf.squeeze(a)     : (2, 3)
Shape of tf.squeeze(a,[2]) : (1, 2, 3)


### stack

Appends n tensors (of same shape and type). Creates a new dimension along the axis where it is being stacked (with size of axis equal to number of tensors being stacked).

In [132]:
a=tf.constant([[1,2],[3,4],[5,6]])
b=tf.constant([[11,12],[13,14],[15,16]])
c=tf.constant([[21,22],[23,24],[25,26]])
d=tf.constant([[31,32],[33,34],[35,36]])
print(a.shape, b.shape, c.shape, d.shape)
print(a)

(3, 2) (3, 2) (3, 2) (3, 2)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


Here we are stacking 4 tensors

In [130]:
stacked_tensors = tf.stack([a,b,c,d], axis=2)
print('Shape of stacked tensors:', stacked_tensors.shape)
print(stacked_tensors)

Shape of stacked tensors: (3, 2, 4)
tf.Tensor(
[[[ 1 11 21 31]
  [ 2 12 22 32]]

 [[ 3 13 23 33]
  [ 4 14 24 34]]

 [[ 5 15 25 35]
  [ 6 16 26 36]]], shape=(3, 2, 4), dtype=int32)


In [131]:
stacked_tensors = tf.stack([a,b,c,d], axis=1)
print('Shape of stacked tensors:', stacked_tensors.shape)
print(stacked_tensors)

Shape of stacked tensors: (3, 4, 2)
tf.Tensor(
[[[ 1  2]
  [11 12]
  [21 22]
  [31 32]]

 [[ 3  4]
  [13 14]
  [23 24]
  [33 34]]

 [[ 5  6]
  [15 16]
  [25 26]
  [35 36]]], shape=(3, 4, 2), dtype=int32)


### tile

In [150]:
var1=tf.constant([[[1,2],[3,4],[5,6]]])
print('Shape of input:', var1.shape)
print(var1)

Shape of input: (1, 3, 2)
tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]], shape=(1, 3, 2), dtype=int32)


Here we see that **var1** is a 3 dimensional Tensor. So to tile it, we need to pass a tensor of size 3 to the argument *multiples* of tile, which specifies how many times to repeat the corresponding dimension. 

**output_shape = input_shape * multiples**

In [149]:
repeat_factor=[2,1,3]
tiled_var1 = tf.tile(var1, multiples=repeat_factor)
print('Repeat factor:', repeat_factor)
print('Shape of tiled output:', tiled_var1.shape)
print(tiled_var1)

Repeat factor: [2, 1, 3]
Shape of tiled output: (2, 3, 6)
tf.Tensor(
[[[1 2 1 2 1 2]
  [3 4 3 4 3 4]
  [5 6 5 6 5 6]]

 [[1 2 1 2 1 2]
  [3 4 3 4 3 4]
  [5 6 5 6 5 6]]], shape=(2, 3, 6), dtype=int32)


### transpose

In [156]:
a = tf.constant([[[ 1,  2],
                  [ 3, 4],
                  [5,  6]],
                 [[ 7,  8],
                  [9, 10],
                  [11, 12]],
                 [[13, 14],
                  [15, 16],
                  [17, 18]],
                 [[19,20],
                  [21,22],
                  [23,24]]])
print('Shape of a:', a.shape)
print(a)

Shape of a: (4, 3, 2)
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]], shape=(4, 3, 2), dtype=int32)


By default transpose reverses the dimensions

In [158]:
transposed_a = tf.transpose(a)
print('Shape of transposed a:', transposed_a.shape)
print(transposed_a)

Shape of transposed a: (2, 3, 4)
tf.Tensor(
[[[ 1  7 13 19]
  [ 3  9 15 21]
  [ 5 11 17 23]]

 [[ 2  8 14 20]
  [ 4 10 16 22]
  [ 6 12 18 24]]], shape=(2, 3, 4), dtype=int32)


In [162]:
print(a)

tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]], shape=(4, 3, 2), dtype=int32)


In [ ]:
We can also specify how the move the dimensions by passing the argument perm to transpose.

In [161]:
perm=[0,2,1]
transposed_a = tf.transpose(a, perm=perm)
print('Shape of a:', a.shape)
print('permute dimensions in the format:',perm)
print('Shape of transposed a:', transposed_a.shape)
print(transposed_a)

Shape of a: (4, 3, 2)
permute dimensions in the format: [0, 2, 1]
Shape of transposed a: (4, 2, 3)
tf.Tensor(
[[[ 1  3  5]
  [ 2  4  6]]

 [[ 7  9 11]
  [ 8 10 12]]

 [[13 15 17]
  [14 16 18]]

 [[19 21 23]
  [20 22 24]]], shape=(4, 2, 3), dtype=int32)


### unstack

In [166]:
a=tf.constant([[1,2],[3,4],[5,6]])
b=tf.constant([[11,12],[13,14],[15,16]])
c=tf.constant([[21,22],[23,24],[25,26]])
d=tf.constant([[31,32],[33,34],[35,36]])
stacked_tensors = tf.stack([a,b,c,d], axis=0)
print(a.shape)
print(stacked_tensors.shape)
print(stacked_tensors)

(3, 2)
(4, 3, 2)
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[11 12]
  [13 14]
  [15 16]]

 [[21 22]
  [23 24]
  [25 26]]

 [[31 32]
  [33 34]
  [35 36]]], shape=(4, 3, 2), dtype=int32)


When we unstack along a particular dimension, n different tensors are created(where n=size of the axis being unstacked). Each tensor will have the shape similar to the original tensor (with the axis being dropped).

Eg: If original shape was (4,3,2) and we unstack along axis 1 then it creates 3 different tensors each of shape (4,2)

In [170]:
unstacked = tf.unstack(stacked_tensors, axis=1)
print('Number of tensors created:', len(unstacked))
print('Size of each tensors:', unstacked[0].shape)

Number of tensors created: 3
Size of each tensors: (4, 2)


In [171]:
print(unstacked)

[<tf.Tensor: id=488, shape=(4, 2), dtype=int32, numpy=
array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32]], dtype=int32)>, <tf.Tensor: id=489, shape=(4, 2), dtype=int32, numpy=
array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34]], dtype=int32)>, <tf.Tensor: id=490, shape=(4, 2), dtype=int32, numpy=
array([[ 5,  6],
       [15, 16],
       [25, 26],
       [35, 36]], dtype=int32)>]
